name = "HomotopyOpt"
uuid = "8c5e0f79-7402-43d4-9c5c-e1bde87b1895"
authors = ["Matthias Himmelmann <matthias.himmelmann@outlook.de", "Alex Heaton <alexheaton2@gmail.com>"]
version = "0.2"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
ForwardDiff = "0.10"
HomotopyContinuation = "2.9"
Plots = "1.39"
julia = "^1.9"
